version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: articles
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5433:5432"

volumes:
  db:
    driver: "local"